### ISSUE TITLE
GetUpdates failure on Restricted chatMember

### ISSUE THREAD

**Issue by Kright** [bot4s/telegram#119]
No value found for 'Restricted'

com.bot4s.telegram.models.MemberStatus doesn't have "Restricted" MemberStatus. It was added in 5.3: 
https://core.telegram.org/bots/api#chatmember

**Comment by ex0ns** [comment]
Thanks for reporting that, I have created a fix, do you have a quick Snippet I could use to test this behavior ? I don't have a super group ready to tests that right now.

Otherwise could you try to use a snaptshot version ?

**Comment by Kright** [comment]
Sorry, I cannot check how code is working. My bot tried to get update, failed each time and tried again many times. I fixed this by writing primitive bot in python, which consumed this update. After that scala bot is working fine.

**Comment by ex0ns** [comment]
Ok, thanks for reporting that, I've tested it and it should not be an issue anymore. I'll do a release this weekend
