### ISSUE TITLE
SetChatAdministratorCustomTitle still has userId: Int instead of Long

### ISSUE THREAD

**Issue by makkarpov** [bot4s/telegram#123]
https://github.com/bot4s/telegram/blob/master/core/src/com/bot4s/telegram/methods/SetChatAdministratorCustomTitle.scala#L14

This class seems to have old `userId: Int` field and not have migrated to `Long` userIds.

**Comment by ex0ns** [comment]
Good catch thanks ! Fixed in version 5.0.3

**Comment by ex0ns** [comment]
https://github.com/bot4s/telegram/releases/tag/v5.0.3
