### ISSUE TITLE
Bot silently stops receiving updates when it gets a message that fails to parse

### ISSUE THREAD

**Issue by makkarpov** [bot4s/telegram#143]
Well, that's not funny anymore. It happened **again**, one more time, and it happened countless times before. The bot just got **another** message with slightly modified JSON markup (games this time) that it failed to parse. And it **again** just stopped processing all updates, even those that were correct.

Bot was in polling mode.

<details>
<summary>Failing message</summary>

```json
{
  "update_id": 16538441,
  "edited_message": {
    "message_id": 1015764,
    "from": {
      "id": 1599103365,
      "is_bot": false,
      "first_name": "m0unteni [block toxic]",
      "username": "m0unteni"
    },
    "chat": {
      "id": -1000123456,
      "title": "Group title",
      "username": "group_username",
      "type": "supergroup"
    },
    "date": 1637011117,
    "edit_date": 1637011143,
    "game": {
      "title": "Keep it UP",
      "text": "Top Players\n1. m0unteni [block toxic] – 3",
      "text_entities": [
        {
          "offset": 0,
          "length": 11,
          "type": "bold"
        },
        {
          "offset": 40,
          "length": 1,
          "type": "bold"
        }
      ],
      "description": "Time for some football freestyle! Keep it UP!",
      "photo": [
        {
          "file_id": "AgACAgQAAxUAAWGSzsc6ls4XQ4kPR49ns9fbCbp8AAIKrTEbtmhxUSW6OTezqSMYAQADAgADcwADIgQ",
          "file_unique_id": "AQADCq0xG7ZocVF4",
          "file_size": 1360,
          "width": 90,
          "height": 51
        },
        {
          "file_id": "AgACAgQAAxUAAWGSzsc6ls4XQ4kPR49ns9fbCbp8AAIKrTEbtmhxUSW6OTezqSMYAQADAgADbQADIgQ",
          "file_unique_id": "AQADCq0xG7ZocVFy",
          "file_size": 12556,
          "width": 320,
          "height": 180
        },
        {
          "file_id": "AgACAgQAAxUAAWGSzsc6ls4XQ4kPR49ns9fbCbp8AAIKrTEbtmhxUSW6OTezqSMYAQADAgADeAADIgQ",
          "file_unique_id": "AQADCq0xG7ZocVF9",
          "file_size": 26959,
          "width": 640,
          "height": 360
        }
      ],
      "animation": {
        "file_name": "animation.mp4",
        "mime_type": "video/mp4",
        "duration": 5,
        "width": 320,
        "height": 180,
        "thumb": {
          "file_id": "AAMCBAADFQABYZLOx2VPMYUFnXKujlkcc_fU7r0AAtUEAAK2aHFRaML43E0g8oUBAAdzAAMiBA",
          "file_unique_id": "AQAD1QQAArZocVF4",
          "file_size": 1569,
          "width": 90,
          "height": 50
        },
        "file_id": "CgACAgQAAxUAAWGSzsdlTzGFBZ1yro5ZHHP31O69AALVBAACtmhxUWjC-NxNIPKFIgQ",
        "file_unique_id": "AgAD1QQAArZocVE",
        "file_size": 95370
      }
    },
    "reply_markup": {
      "inline_keyboard": [
        [
          {
            "text": "Play Keep it UP!",
            "callback_game": {}
          }
        ]
      ]
    },
    "via_bot": {
      "id": 280713127,
      "is_bot": true,
      "first_name": "Gamee",
      "username": "gamee"
    }
  }
}
```
</details>

Serialization mechanism where one failing message could block all update queue is a huge problem and can lead to silent denial-of-service scenarios.

**Comment by ex0ns** [comment]
Thanks for raising this issue, I can't spot what is wrong in the JSON yet, but I totally agree that we should not allow an new/unknown message to make the whole update process fail.

I can't test it right now, but the easiest fix in the meantime might be to override the `pollingGetUpdates` method in your bot:

```scala
  def pollingGetUpdates(offset: Option[Long]): F[Seq[Update]] =
    request(
      GetUpdates(
        offset,
        timeout = Some(pollingTimeout.toSeconds.toInt),
        allowedUpdates = allowedUpdates
      )
    )
  ```
And add some error catching here. However as the error handling will be done at the `GetUpdates` level, you will not get the updates if a single one in the "group" fails.... This is better than nothing but still not perfect...

Another idea might be to create a custom decoder for `Seq[Update]` that would correctly deal with error in the underlying updates, without failing the whole de-serialization.

I'm trying to think of a best way to deal with that but right now I would go with either of the two solution listed above

**Comment by makkarpov** [comment]
Yeah, that is the main issue - when you have "poisonous" update in the queue, you can't get anything else before that update expires.

My suggestion (which however will break backward compatibility) is to replace `Seq[Update]` to `Seq[Try[Update]]` in root `GetUpdates` response. Then create a serializer that will wrap inner `Update` serializer and catch an error there, transforming it to Try object. So single deserialization failure won't result in failure of whole request.

Optionally wrapped serializer can try to decode at least update id in case of failure, so that erroneous update can be skipped.

**Comment by ex0ns** [comment]
Yes, this would be the best way to handle it in my opinion, this will have to be done in 3 steps IMO:

1. take the JSON and extract the updates into a Seq[Json]
2. Convert each json into a Try[T]
3. Keep only the successes

This way we will not break compatibility, but on the other hand, the errors will not be seen either, this is not perfect... I guess that returning a try might be a solution here (or let the user choose the behavior they want)

**Comment by makkarpov** [comment]
Well, this is rather major issue (users can DoS arbitrary bots by just adding them to group and playing a game in that group), so it may worth breaking compatibility. Most people don't use raw `GetUpdates` request, they just extend `Polling` trait which won't be affected by this change.

Keeping only successes means that you can't skip failing updates. If you don't flush the queue properly, long polling will stop working and will return response immediately, which will eventually make bot flood Telegram servers with requests.

**Comment by ex0ns** [comment]
Totally agree, I will definitely work on this by the end of the weekend, I've though of another solution, that could be decent as well, but I would like to have your idea on that:

```scala
  implicit val updateDecoder: Decoder[Update] =
    deriveDecoder[Update] or Decoder.instance { h =>
      for {
        id <- h.get[Long]("updateId")
      } yield Update(updateId = id)
    }
  ```
  
 We could have a decoder that tries to decode the Update, or only retrieve the `updateId` from it so the client would behave correctly. The downside is that it does not enable the use to catch and see the errors clearly (but we can also add some logging on the library side. It would also require to change/remove a bit the assertion made in `Update.scala`:
 
 ```scala
   require(
    Seq[Option[_]](
      message,
      editedMessage,
      channelPost,
      editedChannelPost,
      inlineQuery,
      chosenInlineResult,
      callbackQuery,
      shippingQuery,
      preCheckoutQuery,
      poll,
      myChatMember,
      chatMember
    ).count(_.isDefined) == 1,
    "Exactly one of the optional fields should be used"
  )
  ```
  
  Because the decoding would fail with only an ID.
  The other solution I see it migrating all of this to a `Seq[Either[Option[Long], Update]]`. It would give us two levels to handle the errors:
 
`Right(update)` => success case, everything went fine 
`Left(Some(id))` => the update had an idea, but we fail to parse the message
`Left(none)` => This should probably never happen, it means that the Update did not contain a update_id

However I'm not even sure that we need to support the last case, as it would probably mean that something really wrong is going on with the API (but at least we would not crash in the client)
 
 What do you think ?

**Comment by makkarpov** [comment]
Looks good!

Typing can be made clearer by introducing custom sealed trait instead of doing 4-th level of generics, like that:
```
sealed trait ParsedUpdate
object ParsedUpdate {
  case class Failure(updateId: Long, cause: DecodingFailure) extends ParsedUpdate
  case class Success(update: Update) extends ParsedUpdate
}
```

Conversion from raw update type to wrapped should be rather straightforward and can be done by wrapping a decoder object.

As for that assert: if assertion failure would result in circe `DecodingFailure` - I don't think that there is a need for removal. Anyway update with an unknown client (so that every other field is `None`) is a malformed update from library's perspective.

If decoder is unable to decode even `updateId` - I think that whole request should fail because something really bad is happening.

**Comment by ex0ns** [comment]
If you want to give a try to the update, I've published a snapshot 
https://oss.sonatype.org/content/repositories/snapshots/com/bot4s/telegram-core_2.12/5.0.4-2b00e0cf-SNAPSHOT/

I'll probably go over the PR one more time to make sure everything is ok and will do a release tonight or tomorrow

**Comment by ex0ns** [comment]
@makkarpov About the original error, the The decoder seems to fail on `"callback_game": {}`. 
This was indeed an issue on the serialization/deserialization of the case object `CallbackGame` (which is an empty object). What was serialized as `{"CallbackGame": {}}` instead of `{}`

**Comment by ex0ns** [comment]
5.1.0 published with the fix, closing this for now. Feel free to re-open an issue if this is still a problem
