### ISSUE TITLE
Help to remove menu.

### ISSUE THREAD

**Issue by AlexGruPerm** [bot4s/telegram#260]
Hello. I was plaing with API and now have menu and don't know how to remove it.
Could you suggest me something please!?

![image](https://user-images.githubusercontent.com/33136423/189762717-a73ce981-abdc-47d8-b609-f452ee04566d.png)

**Comment by ex0ns** [comment]
Did you check getChatMenuButton?
Maybe https://core.telegram.org/bots/api#menubuttondefault

```
If a menu button other than [MenuButtonDefault](https://core.telegram.org/bots/api#menubuttondefault) is set for a private chat, then it is applied in the chat. Otherwise the default menu button is applied. By default, the menu button opens the list of bot commands.
```


Did you set any `commands` in your bot?
