### ISSUE TITLE
Proxy basic authentification

### ISSUE THREAD

**Issue by rurikovich** [bot4s/telegram#315]
Can you add  to ScalajHttpClient.scala basic authentification  with login password ?

you just need to add
  ```
  val basicAuth = s"$proxyLogin:$proxyPassword"
    val basicAuthBase64 = BaseEncoding.base64().encode(basicAuth.getBytes(Charsets.UTF_8))


        scalajRequest
          .timeout(connectionTimeoutMs, readTimeoutMs)
          .proxy(proxy)
          .header("Proxy-Authorization", s"Basic $basicAuthBase64")
          .asString
```

**Comment by rurikovich** [comment]
I created pull request https://github.com/bot4s/telegram/pull/316

please accept it as soon as possible

**Comment by ex0ns** [comment]
I just notice that you closed the PR, we you able to make it work in the end ?
Should I close this issue as well ?
