### ISSUE TITLE
Upcoming refactor

### ISSUE THREAD

**Issue by mukel** [bot4s/telegram#51]
I'm planning a major refactor, these are some of the planned changes/features, please leave your feature in the comments.
 - [x] ~~Remove Akka from dependencies, add it as an optional backend.~~ ~~ Ship Akka as default backend (convenience wins) ~~, ship ScalajHttp as default, allow other backends (RossHttp).
 - [x] Update to Telegram Bot API 3.5 (WIP)
 - [X] Provide other backend alternatives (Scalaj-http)
 - [ ] Improve error handling.
 - [ ] Provide composable request handlers (retry, full log, chain requests...)
 - [ ] Add proper examples for Heroku, Google App Engine...
 - [X] Support for Scala.js, 
 - [X] Support for several backends e.g. AkkaHttp, Sttp, Scalaj aand custom ones.
 - [X] Transparent JSON marshalling, no need for implicits nor reflection.

**Comment by outime** [comment]
Thanks a lot for this cool lib!

**Comment by laughedelic** [comment]
How hard would it be to support Scala.js?

**Comment by mukel** [comment]
Well, JSON serialization depends on reflection and json4s which does not support Scala.js , I've been playing with circe; which supports Scala.js but IMHO it's not quite there yet in terms of working out-of-the-box; some serialization boilerplate is needed.
Except for the JSON stuff (and some serialization) all other components can be ported easily.

**Comment by laughedelic** [comment]
I see. What do you think about using [µPickle](http://www.lihaoyi.com/upickle/) for JSON serialization?

**Comment by mukel** [comment]
It will be uber cool to run bots on the browser via Scala.js
uPickle looks good, I'll look into it. Stay tuned!

**Comment by laughedelic** [comment]
Yeah, I was also thinking about running a bot on AWS Lambda on Node.js.

**Comment by mukel** [comment]
Success!!! Finally managed to port all the serialization to circe, enough to run a simple bot (without multipart uploads). It's far from finished but workable.

**Comment by mukel** [comment]
I have a working prototype using [RosHttp](https://github.com/hmil/RosHTTP) with some quirks e.g. cannot download files. It can be fixed but the library seems to be abandoned. Any good http client library for ScalaJs?

**Comment by laughedelic** [comment]
I don't know, haven't used any. Have you tried asking on the [scala-js gitter channel](https://gitter.im/scala-js/scala-js)?

**Comment by laughedelic** [comment]
[sttp](https://github.com/softwaremill/sttp) just got Scala.js support: https://twitter.com/adamwarski/status/1001527624202686464

**Comment by TobsCore** [comment]
@mukel You might wanna check out https://github.com/lihaoyi/requests-scala as it looks pretty sweet.
