### ISSUE TITLE
info.mukel.telegrambot4s.api.TelegramApiException: Not Found

### ISSUE THREAD

**Issue by dimparf** [bot4s/telegram#60]
Hi!
I'm making a request with SendMessage, but info.mukel.telegrambot4s.api.TelegramApiException: Not Found
I looked into the code of info.mukel.telegrambot4s.methods.ApiRequest[R] and found this:
  def methodName: String = getClass.getSimpleName.reverse.dropWhile(_ == '$').reverse
but this code return SendMessage, expected sendMessage (in Telegram API).

**Comment by mukel** [comment]
The Telegram Bot API is [case-insensitive](https://core.telegram.org/bots/api#making-requests):
Maybe the `chat_id` is not valid anymore. How are you sending the `SendMessage` request?
