### ISSUE TITLE
Dependency isn't available in the repo

### ISSUE THREAD

**Issue by synnz** [bot4s/telegram#65]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.bot4s#telegram-core_2.12;4.0.0-RC1: not found
[warn] 	:: com.bot4s#telegram-akka_2.12;4.0.0-RC1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by mukel** [comment]
I'll publish RC1 soon, staging is kind of convenient for me but not so for others.

**Comment by mukel** [comment]
Released RC1 to Maven, check the [updated instructions](https://github.com/bot4s/telegram#as-sbtmill-dependency). Please do report bugs or usability issues, I can also provide quick examples for some functionalities on demand.
