### ISSUE TITLE
Bot starts, but doesn't receive updates

### ISSUE THREAD

**Issue by emanueloliveira23** [bot4s/telegram#71]
Hi.

I'm developing a bot to send messages to a channel. 

Locally, while I develop the bot and run it, it works fine and receives all commands.
But in a production environment, were a firewall blocks all requests by default, it doesn't work. My bot isn't receiving messages or commands.

I already allowed "api.telegram.org:443" in the firewall. This liberation works. I can send requests to it via telnet. But wasn't enough.

There another port or address that I need allow?

**Comment by mukel** [comment]
If you are using polling api.telegram.org:443 is enough (for everything).
 What do you mean with "send requests via telnet"? Are using Webhooks?  Can you elaborate more on your setup? Does any of the examples works on your prod environment?

**Comment by emanueloliveira23** [comment]
Hi @mukel !

I used telnet just to test the connection and check if firewall really allowed the endpoint... And works.

About the prod. environment (overviewed): my bot is running on application in a docker container in a kubernetes Pod. No replications were made.

I also checked the keepalive timeouts and seems to be OK.

Locally, in development environment, It works fine. 

There some errors logs about the connection to Telegram Bot API?

**Comment by emanueloliveira23** [comment]
@mukel 

Follow some verbose outputs from wget and curl:

**wget**
```
$ wget https://api.telegram.org/bot<token>/getMe 
--2019-03-22 13:23:24--  https://api.telegram.org/bot<token>/getMe
Resolving api.telegram.org (api.telegram.org)... 149.154.167.220, 2001:67c:4e8:f004::9
Connecting to api.telegram.org (api.telegram.org)|149.154.167.220|:443... connected.
```

**curl**
```
$ curl -v https://api.telegram.org/bot<token>/getMe
*   Trying 149.154.167.220...
* TCP_NODELAY set
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```

**Comment by emanueloliveira23** [comment]
@mukel 

The problem isn't in your library.

Thanks for that.

Great work!

**Comment by mukel** [comment]
Good to hear you found the culprit. Please do spawn an issue if you have any further trouble with your bot.

**Comment by emanueloliveira23** [comment]
Okay, @mukel .

Thanks for the library and your availability.
