### ISSUE TITLE
Gifs in v.3.0.16

### ISSUE THREAD

**Issue by benkio** [bot4s/telegram#75]
Hi,
There's a way to send gifs in the older version 3.16, apart from senting the Gif URL?
Cheers

**Comment by mukel** [comment]
[SendAnimation](https://github.com/bot4s/telegram/blob/d8c54b8f818ee5e168852c4044dc87cf341e279c/core/src/com/bot4s/telegram/methods/SendAnimation.scala) was added in v4.
FOr v3, you can try with [SendDocument](https://github.com/bot4s/telegram/blob/1d84c5ddc89665524e040b2b4b6d8ec0f33bda84/core/src/main/scala/info/mukel/telegrambot4s/methods/SendDocument.scala), passing the contents in the [InputFile](https://github.com/bot4s/telegram/blob/1d84c5ddc89665524e040b2b4b6d8ec0f33bda84/core/src/main/scala/info/mukel/telegrambot4s/models/InputFile.scala). Can you please try if `SendDocument` accepts GIFs? e.g.
```scala
val gif = InputFile("my.gif", bytes)
request(SendDocument(msg.source, gif))
```

**Comment by benkio** [comment]
I tried, but the bot sent a file as a result

**Comment by benkio** [comment]
Works,
I saved the gif in the wrong way. 
Thanks
