### ISSUE TITLE
Check webhook before setting new one

### ISSUE THREAD

**Issue by aaabramov** [bot4s/telegram#79]
**Problem:**
We are using webhooks and have scaling environment (e.g. k8s) and we scale our bot app from 1 to 3+ instances. They are launched in parallel and each one tries to set the same webhook via `setWebhook`.
And as expected Telegram responds with `429 Too Many Requests`.

**Solution:**
Before setting the webhook execute `getWebhookInfo` method and compare it with `com.bot4s.telegram.methods.SetWebhook` parameters.

**Concerns:**
- if `certificate` was changes than there is no way to find this out
- there still might be races between instances but I believe Telegram handles this method as atomic

Or at least we can provide some sort of parameter which configures this behavior.

I am fine with submitting PR after we agree on solution.

**Comment by danilbykov** [comment]
Don't understand how your proposal solves this scenario:
server1 sends GetWebhookInfo and receives that hook is not set
server2 GetWebhookInfo and receives that hook is not set
server2 sets hook because hook is not set
server1 also sets hook because it is not set

So you get two hooks simultaneously.

**Comment by aaabramov** [comment]
Yes, you are right. That is why I mentioned it as a concern.
Any ideas from you?

**Comment by danilbykov** [comment]
Any ideas about what? About solving issue? As I said, take some SQL database, some in-memory database (I don't know which one is available in your environment) which supports atomic updates. Then allocate some kind of atomic integer variable. Let's call it `X`.

When server is started, it checks X. If `currentTime - X` is more than 5 minutes then tries to write `currentTime` into X atomically. If write is successful (which means that current server "wins" other servers) then try to setup hook in Telegram. While this server is running it should set current time to `X` each 1 minute.

All servers should check `X` periodically. If it is not updated more then 5 minutes then try to create hook again.

**Comment by aaabramov** [comment]
@danilbykov Thanks, I have already solved that in my environment.
I mean solving this in scope of library.

> then try to setup hook in Telegram

The point is that code with setting webhook is in library itself. The only option to avoid this is to override `com.bot4s.telegram.api.Webhook#run`.
