### ISSUE TITLE
4.4.0-RC1: UnsupportedAkkaVersion

### ISSUE THREAD

**Issue by aaabramov** [bot4s/telegram#80]
For dependencies:

```
"com.bot4s"           %% "telegram-core" % "4.4.0-RC1"
"com.bot4s"           %% "telegram-akka" % "4.4.0-RC1"
```

I am getting runtime error:
```
Exception in thread "main" akka.UnsupportedAkkaVersion: Current version of Akka is [2.5.22], but akka-http requires version [2.5.23]
```

![image](https://user-images.githubusercontent.com/11317222/64970652-ecc8c300-d8ae-11e9-941a-47eefd55175b.png)

**Comment by mukel** [comment]
This has been fixed in master but not released, adding the akka-http dependency with the right version fixes the issue.
