### ISSUE TITLE
What SttpBackends is ??

### ISSUE THREAD

**Issue by kon3gor** [bot4s/telegram#87]
I'm really new to Scala and I'm trying to make a bot using this lib. But I can't, because there is a  line `implicit val backend = SttpBackends.default` but there is no class called SttpBackends in this lib. I downloaded sttp lib, but there is no such class there too. So, I can't make even example bot. Where can I find SttpBackends class ?

**Comment by danilbykov** [comment]
This class comes from this file:
https://github.com/bot4s/telegram/blob/master/examples/src-jvm/SttpBackends.scala#L3-L5

**Comment by kon3gor** [comment]
> This class comes from this file:
> https://github.com/bot4s/telegram/blob/master/examples/src-jvm/SttpBackends.scala#L3-L5

Thanks
