### ISSUE TITLE
Bot stops receiving updates when receives game message

### ISSUE THREAD

**Issue by makkarpov** [bot4s/telegram#91]
**Steps to reproduce**:

1. Create a bot with 4.4.0-RC2 version of library and polling mode (if it's important, maybe it reproduces with webhook too). AkkaHttp and OkHttp backends were tried, both producing same result.
2. Send some game to the bot (e.g. via `@gamee ....`).
3. Send some other messages to the bot.

**Expected behavior**:

Bot receives both game message and all following messages.

**Actual behavior**:

Bot is stuck forever and receives neither game nor any subsequent messages. Queue needs to be flushed manually. No errors or messages are printed, bot just stops working and stucks until the message is flushed or expired.

**Comment by makkarpov** [comment]
More specifically, `GetUpdates` fails with decoding issue, but somehow fails silently, as nothing is shown in logs. This error is only visible when you invoke `GetUpdates` request directly:

`DecodingFailure(CNil, List(DownField(callbackGame), DownArray, DownArray, DownField(inlineKeyboard), DownField(replyMarkup), DownField(editedMessage), DownArray, DownField(result)))`

**Comment by makkarpov** [comment]
Replacing CallbackGame.scala with 

```
/** A placeholder, currently holds no information. Use BotFather to set up your game.
  */
case class CallbackGame()

object CallbackGame extends CallbackGame()
```

seems to fix it.

**Comment by makkarpov** [comment]
Is this project dead? @mukel?

Telegram API has accumulated considerable amount of updates.

**Comment by mukel** [comment]
Sadly I don't have time nor will power to continue maintaining it. The Scala 3 transition will be a nightmare for library authors... I will kindly transfer ownership to an interested dev, including the [bot4s GitHub org](https://github.com/bot4s/) and the [bot4s.com](bot4s.com) domain.

**Comment by makkarpov** [comment]
I don't need full ownership, but permission to commit here would be useful. Since I'm now using [my separate fork with fixes](https://github.com/makkarpov/telegrambot4s-fix), which is published to private Maven.

It would be useful to merge these fixes here (either directly or by pull request).

**Comment by makkarpov** [comment]
Ok, this happened again, this time with different message. Bot just silently stuck until someone noticed that it isn't getting updates.

@mukel Please give ownership, this library is increasingly getting outdated.

**Comment by makkarpov** [comment]
**Now every joining or leaving user breaks this library**. Breaks silently, no log messages, nothing, nothing at all.

This is related to recently introduced changes of reporting chat member changes.

The code in this repository is critically outdated and not usable anymore.

**Comment by ex0ns** [comment]
@makkarpov Hi, I'm working on updating this library, I saw on your fork that you did some fixes regarding GetUpdate, CallbackGame and id as Long.

Would you agree to open Pull requests against this repo to include those changes ?
If you don't have the time or can't right now, I can also take care of that (I'll cherry pick the commit from your fork).

Thanks

**Comment by makkarpov** [comment]
Unfortunately I can't do it right now, but feel free to copy-paste or cherry-pick the code.

The by the way the main issue of logging going to nowhere (with SLF4J i see no output) is not fixed in my branch.

**Comment by ex0ns** [comment]
Ok thanks ! I think I've already fixed most of the issue in the repo in the past few days.
